init:
  - git config --global core.autocrlf input

version: 0.1.{build}

skip_tags: true

build_script:
  - cmd: build.cmd

test: off

artifacts:
  - path: Build\Packages\*.nupkg

cache:
  - packages -> **\packages.config

services:
  - mssql2014

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
